### ISSUE TITLE
希望增加右上角的“免费抽奖”任务

### ISSUE THREAD

**Issue by LvDeShei** [yyt666666/AutoJS_DailyAppTask#1]
希望增加右上角的“免费抽奖”任务
![aeb62eb7b84133a229712a0e55db1f5](https://user-images.githubusercontent.com/49177549/197341692-18a3c3b5-74d5-4814-b215-1495a1892ec0.jpg)

**Comment by yyt666666** [comment]
这里的金币太少了，每个任务才给1000币，写起来还麻烦，暂时不考虑做了

**Comment by LvDeShei** [comment]
好的大佬，感谢回复！
