### ISSUE TITLE
大佬，看到更新了，感谢，但是不能用呢

### ISSUE THREAD

**Issue by LvDeShei** [yyt666666/AutoJS_DailyAppTask#3]
调用分身走到这一步就不动了，然后等待一会就又开始调用下一个分身了
![36070ac4d42834acf508305924c42a9](https://user-images.githubusercontent.com/49177549/209548998-e050aae2-22b2-4db9-b4b8-e7806284d942.jpg)

**Comment by yyt666666** [comment]
已修复入口关键字
